# Generated by Django 5.1.4 on 2025-01-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('game_name', models.TextField(default='undef game')),
                ('game_img', models.TextField(default='misc/images/default.png')),
                ('is_multiplayer', models.BooleanField(default=False)),
                ('genre', models.TextField(default='NO genre')),
                ('language', models.TextField(default='English')),
                ('date', models.DateField()),
                ('developer', models.TextField(default='me')),
                ('specialties', models.TextField(default='no specialties')),
                ('description', models.TextField(default='cool game')),
                ('price', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
