# Generated by Django 5.1.4 on 2025-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('game_name', models.TextField(default='undef game')),
                ('game_img', models.TextField(default='misc/images/default.png')),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
