# Generated by Django 5.1.4 on 2025-01-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalog',
            table='shrot_desc_games',
        ),
    ]
